#title in header
title: "Hi PalaPalado."

#main info
#owner
owner: "ShengChih"
email: ms0529756@gmail.com
info: "è‡ºå—äººï¼Œå±…ä½åœ¨å°ç£çš„ç¶²ç«™å·¥ç¨‹å¸« ğŸ‡¹ğŸ‡¼"
#description
desc: ""

#menu
menu:
  Posts: /archives
  About: /about

#index/main page max show posts (in number)
max_post: 4

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
github: https://github.com/ShengChih
instagram: https://instagram.com/ms0529756

# Misc
nanobar: /js/nanobar.min.js
switch_light: â˜€ï¸
switch_dark: ğŸŒ‘

# Picture enlargement
picjs: /js/pic.min.js

# favicon
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname: https-shengchih-github-io

# About resu,e
resume:
  name: Sammy, Chu
  jobtitle: è³‡æ·±å·¥ç¨‹å¸«
  contact:
    - icon: fa-envelope
      text: ms0529756@gmail.com
    - icon: fa-globe
      text: Blog
      link: https://shengchih.github.io/
    - icon: fa-github
      text: Github
      link: https://github.com/ShengChih
  education:
    - university: åœ‹ç«‹è‡ºç£å¸«ç¯„å¤§å­¸ National Taiwan Normal University
      duration: Sep 2013 - Aug 2015
      location: Taipei, Taiwan
      major: Computer Science & Information Engineering
    - university: åœ‹ç«‹é«˜é›„ç§‘æŠ€å¤§å­¸ National Kaohsiung University of Science and Technology
      duration: Sep 2008 - Aug 2012
      location: Kaohsiung, Taiwan
      major: Computer Science & Information Engineering
  skills:
    - title: AWS Cloud Service
      items: EC2, RDS, Apigateway, Lambda, S3, Cloudfont,...etc
    - title: Programming language
      items: Python, PHP, NodeJS
    - title: Infrastructure
      items: Docker
    - title: Frameworks
      items: Django, Codeigniter, ReactJS
    - title: NoSQL / SQL
      items: MongoDB, Redis, MySQL, PostgreSQL, SQLite
  experience:
    - title: è³‡æ·±å·¥ç¨‹å¸«
      duration: Jul 2021 - Oct 2022
      company: ä¼Šé›²è°·æ•¸ä½ç§‘æŠ€è‚¡ä»½æœ‰é™å…¬å¸ eCloudvalley Digital Technology Co., Ltd.
      description: SCM ä¾›æ‡‰å•†ç®¡ç†éˆç³»çµ±<br>OCR ç³»çµ±æ•´åˆ<br>ESG ç¢³å¹³å°ç®¡ç†ç³»çµ±<br>
    - title: è»Ÿé«”å·¥ç¨‹å¸«
      duration: Aug 2019 - Mar 2021
      company: æ¾æœè³¼ç‰©è‚¡ä»½æœ‰é™å…¬å¸ Mobix Corporation, Inc.
      description: æ¾æœç¶²ç«™å‰å¾Œå°ç³»çµ±é–‹ç™¼
    - title: è»Ÿé«”å·¥ç¨‹å¸«
      duration: Sep 2015 - Apr 2019
      company: ç¶²æ“è³‡è¨Šè»Ÿé«”è‚¡ä»½æœ‰é™å…¬å¸ Openfind Information Technology, Inc.
      description: é›²ç«¯å„²å­˜æœå‹™ç³»çµ± SecuShare / ArkEasePro
  projects:
    - name: <a style="color:#1654b9;" href="https://files.fireweedsound.xyz/gnsign">The F2E 4th ä½œå“ - é›»å­ PDF ç°½æ ¸</a>
      description: Week2 é¡Œç›®ï¼Œä¸»è¦ä½¿ç”¨ Typescript & ReactJS CSRï¼Œå¯¦é©— Canvas å¥—ä»¶ & Web Worker ç­‰åŠŸèƒ½
      contribution: ä¸»è¦è²¢ç»è€… / ç¶­è­·è€…
    - name: <a style="color:#1654b9;" href="https://files.fireweedsound.xyz/gsapnewspaper">The F2E 4th ä½œå“ - è¦–å·®æ»¾å‹•è¨­è¨ˆ</a>
      description: Week1 é¡Œç›®ï¼Œä¸»è¦ä½¿ç”¨ Typescript & ReactJS CSRï¼Œå¯¦é©—å‘¨é‚Šç”Ÿæ…‹çš„å¥—ä»¶åŠ imperative é¢¨æ ¼èªæ³•
      contribution: ä¸»è¦è²¢ç»è€… / ç¶­è­·è€…
    - name: <a style="color:#1654b9;" href="https://github.com/Fingerstyle-Taiwan/django-backend">å°ç£ FingerStyle OAuth2.0 é©—è­‰ API</a>
      description: æ­¤ç‚ºé–‹æºå°ˆæ¡ˆï¼Œå¾Œç«¯ Django APIï¼Œåƒ…å¯¦ä½œé©—è­‰ OAuth2.0 token åŠŸèƒ½ï¼Œè² è²¬è®“å‰ç«¯ç‚º SSR Next OAuth ç™»å…¥å¾Œï¼Œç”¨ OAuth2.0 token æ›å– django api token 
      contribution: ä¸»è¦è²¢ç»è€… / ç¶­è­·è€…
    - name: <a style="color:#1654b9;" href="http://djdlfmonhbvcv.cloudfront.net/sign-in">SCM ä¾›æ‡‰å•†ç®¡ç†éˆç³»çµ±</a>
      description: æ•´åˆ SAP ç³»çµ±<br>æµç¨‹åŠå‡ºè²¨åŠŸèƒ½<br>ç™¼ç¥¨åŠè«‹æ¬¾åŠŸèƒ½<br>åˆ†é /æœå°‹ API æ•ˆèƒ½æ”¹å–„ï¼Œå¾ 3min to 20ms
      contribution: ä¸»è¦è²¢ç»è€… / ç¶­è­·è€…
    - name: OCR ç³»çµ±æ•´åˆ
      description: AWS Infra å»ºç½®<br>èªè­‰ç³»çµ±
      contribution: ä¸»è¦ç¶­è­·è€…
    - name: <a style="color:#1654b9;" href="https://scr-sys.s3.us-west-2.amazonaws.com/sign-in.html">ESG ç¢³å¹³å°ç³»çµ± demo</a>
      description: AWS æœå‹™å»ºç½®<br>åŠŸèƒ½é–‹ç™¼ (æ¬Šé™è¨­è¨ˆ|ç¢³ä¿‚æ•¸|ä¼æ¥­|å·¥å» |ç¢³æ’è¨ˆç®—)
      contribution: ä¸»è¦è²¢ç»è€… / ç¶­è­·è€…
    - name: <a style="color:#1654b9;" href="https://pcone.com.tw">æ¾æœå‰å¾Œå°ç³»çµ±</a>
      description: é‡æ§‹æŠ˜æ‰£åŠŸèƒ½<br>æ”¹å–„å•†å“å¿«å–æ©Ÿåˆ¶æ•ˆèƒ½ç´„ 83%<br>è¦çš®çˆ¬èŸ²æ¬å®¶å·¥å…·ï¼Œå°å…¥ 30w+ å•†å“<br>Feed è‡ªå‹•æŠ•æ”¾å»£å‘Šæ•ˆèƒ½æ”¹å–„ 66 % <br>EDM é€šçŸ¥ä¸­å¿ƒè¨­è¨ˆå…¼å¯¦ä½œ<br><a style="color:#1654b9;" href="https://www.pcone.com.tw/newmerchant">æ‹›å•†é </a><br><a style="color:#1654b9;" href="https://www.pcone.com.tw/event/appnewmember/index">æ–°äººç¦®åŒ…</a><br>
      contribution: ä¸»è¦è²¢ç»è€… / ç¶­è­·è€…
    - name: <a style="color:#1654b9;" href="https://aep.office.openfind.com.tw/index.php/login">Secushare Pro</a>
      description: èªè­‰ç³»çµ±<br>å”åŒå·¥ä½œ<br>æª”æ¡ˆåˆ†äº«
      contribution: ä¸»è¦è²¢ç»è€… / ç¶­è­·è€…


