#title in header
title: "Hi PalaPalado."

#main info
#owner
owner: "ShengChih"
email: ms0529756@gmail.com
info: "è‡ºå—äººï¼Œå±…ä½åœ¨å°ç£çš„ç¶²ç«™å·¥ç¨‹å¸« ğŸ‡¹ğŸ‡¼"
#description
desc: ""

#menu
menu:
  Posts: /archives
  About: /about

#index/main page max show posts (in number)
max_post: 4

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
github: https://github.com/ShengChih
instagram: https://instagram.com/ms0529756

# Misc
nanobar: /js/nanobar.min.js
switch_light: â˜€ï¸
switch_dark: ğŸŒ‘

# Picture enlargement
picjs: /js/pic.min.js

# favicon
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname: https-shengchih-github-io

# About resu,e
resume:
  name: Sammy, Chu
  jobtitle: è³‡æ·±å·¥ç¨‹å¸«
  contact:
    - icon: fa-envelope
      text: ms0529756@gmail.com
    - icon: fa-globe
      text: Blog
      link: https://shengchih.github.io/
    - icon: fa-github
      text: Github
      link: https://github.com/ShengChih
  education:
    - university: åœ‹ç«‹è‡ºç£å¸«ç¯„å¤§å­¸ National Taiwan Normal University
      duration: Sep 2013 - Aug 2015
      location: Taipei, Taiwan
      major: Computer Science & Information Engineering
    - university: åœ‹ç«‹é«˜é›„ç§‘æŠ€å¤§å­¸ National Kaohsiung University of Science and Technology
      duration: Sep 2008 - Aug 2012
      location: Kaohsiung, Taiwan
      major: Computer Science & Information Engineering
  skills:
    - title: AWS Cloud Service
      items: EC2, RDS, Apigateway, Lambda, S3, Cloudfont,...etc
    - title: Programming language
      items: Python, PHP, NodeJS
    - title: Infrastructure
      items: Docker
    - title: Frameworks
      items: Django, Codeigniter, ReactJS
    - title: NoSQL / SQL
      items: MongoDB, Redis, MySQL, PostgreSQL, SQLite
  experience:
    - title: è³‡æ·±å·¥ç¨‹å¸«
      duration: Jul 2021 - Oct 2022
      company: ä¼Šé›²è°·æ•¸ä½ç§‘æŠ€è‚¡ä»½æœ‰é™å…¬å¸ eCloudvalley Digital Technology Co., Ltd.
      description: SCM ä¾›æ‡‰å•†ç®¡ç†éˆç³»çµ±<br>OCR ç³»çµ±æ•´åˆ<br>ESG ç¢³å¹³å°ç®¡ç†ç³»çµ±<br>
    - title: è»Ÿé«”å·¥ç¨‹å¸«
      duration: Aug 2019 - Mar 2021
      company: æ¾æœè³¼ç‰©è‚¡ä»½æœ‰é™å…¬å¸ Mobix Corporation, Inc.
      description: æ¾æœç¶²ç«™å‰å¾Œå°ç³»çµ±é–‹ç™¼
    - title: è»Ÿé«”å·¥ç¨‹å¸«
      duration: Sep 2015 - Apr 2019
      company: ç¶²æ“è³‡è¨Šè»Ÿé«”è‚¡ä»½æœ‰é™å…¬å¸ Openfind Information Technology, Inc.
      description: é›²ç«¯å„²å­˜æœå‹™ç³»çµ± SecuShare / ArkEasePro
  projects:
    - name: SCM ä¾›æ‡‰å•†ç®¡ç†éˆç³»çµ±
      description: æ•´åˆ SAP ç³»çµ±<br>æµç¨‹åŠå‡ºè²¨åŠŸèƒ½<br>ç™¼ç¥¨åŠè«‹æ¬¾åŠŸèƒ½<br>
      contribution: ä¸»è¦è²¢ç»è€… / ç¶­è­·è€…
    - name: OCR ç³»çµ±æ•´åˆ
      description: AWS Infra å»ºç½®<br>èªè­‰ç³»çµ±
      contribution: ä¸»è¦ç¶­è­·è€…
    - name: ESG ç¢³å¹³å°ç³»çµ±
      description: AWS æœå‹™å»ºç½®<br>åŠŸèƒ½é–‹ç™¼ (æ¬Šé™è¨­è¨ˆ|ç¢³ä¿‚æ•¸|ä¼æ¥­|å·¥å» |ç¢³æ’è¨ˆç®—)
      contribution: ä¸»è¦è²¢ç»è€… / ç¶­è­·è€…
    - name: æ¾æœå‰å¾Œå°ç³»çµ±
      description: é‡æ§‹æŠ˜æ‰£åŠŸèƒ½<br>æ”¹å–„å•†å“å¿«å–æ©Ÿåˆ¶æ•ˆèƒ½<br>çˆ¬èŸ²æ¬å®¶å·¥å…·<br>Feed è‡ªå‹•æŠ•æ”¾å»£å‘Šæ•ˆèƒ½<br>é€šçŸ¥ä¸­å¿ƒ
      contribution: ä¸»è¦è²¢ç»è€… / ç¶­è­·è€…
    - name: Secushare Pro
      description: èªè­‰ç³»çµ±<br>å”åŒå·¥ä½œ<br>æª”æ¡ˆåˆ†äº«
      contribution: ä¸»è¦è²¢ç»è€… / ç¶­è­·è€…


